/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3_2;

import java.util.Scanner;

public class App {
    /*public String getGreeting() {
        return "Hello World!";
    }*/
    
    public static void main(String[] args) {
       //System.out.println(new App().getGreeting());
       Scanner sc = new Scanner(System.in);
       System.out.print("Dame los grados centigrados: ");
       float gradosC = sc.nextFloat();
       
       float gradosK = gradosC + 273.15f;
       float gradosF = (gradosC*(9/5)) + 32;
       
       System.out.print(gradosC+" grados centigrados son "+gradosK+" grados Kelvin y "+gradosF+" grados Fahrenheit");
       
    }
}
