/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boletin3_1;

import java.util.Scanner;

public class App {
    /*public String getGreeting() {
        return "Hello World!";
    }*/

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        float pTarifa, pPagado, descuento;
        
        Scanner sc = new Scanner(System.in);
        System.out.print("Precio tarifa: ");
        pTarifa = sc.nextInt();
        
        System.out.print("Precio pagado: ");
        pPagado = sc.nextInt();
        
        descuento = ((pTarifa-pPagado)/pTarifa)*100;
        
        System.out.print("El descuento de "+pTarifa+" euros si pago " +pPagado+ " es de "+descuento+"%");
    }
}
